services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: "false"
    ports:
      - 9200:9200
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379