services:
  elasticsearch:
    container_name: hotdeals_elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: "false"
    image: elasticsearch:7.17.4
    ports:
      - 9200:9200
  mongodb:
    container_name: hotdeals_mongodb
    environment:
      - MONGO_INITDB_DATABASE=db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  redis:
    container_name: hotdeals_redis
    image: redis:latest
    ports:
      - 6379:6379