services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: hotdeals_elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: "false"
    ports:
      - 9200:9200
  mongodb:
    image: mongo:4.4
    container_name: hotdeals_mongodb
    environment:
      - MONGO_INITDB_DATABASE=db
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
  redis:
    image: redis:latest
    container_name: hotdeals_redis
    ports:
      - 6379:6379