api-version: "1.0"
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cache:
    redis:
      cache-null-values: false
      time-to-live: PT10M
  data:
    mongodb:
      auto-index-creation: true
      database: db
      #uri: mongodb://localhost:27017
    rest:
      detection-strategy: annotated
#  elasticsearch:
#    rest:
#      uris: localhost:9200
#  redis:
#    host: localhost
#    port: 6379
security:
  firebase-properties:
    # SET YOUR FIREBASE AUTHENTICATION DATABASE URL
    database-url: https://xxxxx-xxxx.firebaseapp.com
  allowed-origins:
    - http://localhost:3000
  allowed-methods:
    - OPTIONS
    - GET
    - PATCH
    - POST
    - PUT
    - DELETE
  # SET THE ADMIN EMAIL ADDRESSES HERE
  super-admins:
    - admin1@gmail.com
    - admin2@gmail.com