api-version: "1.0"
spring:
  threads:
    virtual:
      enabled=true
  main:
    web-application-type: servlet
  task:
    execution:
      virtual-threads: true
  #  cache:
#    redis:
#      enabled: false
#      cache-null-values: false
#      time-to-live: PT10M
  data:
    mongodb:
      auto-index-creation: true
      database: db
      uri: mongodb://127.0.0.1:27018  # uri: mongodb://mongodb:mongodb@host.docker.internal:27017/pet-clinic-reviews
    rest:
      detection-strategy: annotated
#    elasticsearch:
#      rest:
#        uris: http://127.0.0.1:9200
#    redis:
#      host: 127.0.0.1
#      port: 6379
security:
  enabled: true
  #allowed-origins:
  #  - http://localhost:3000
  allowed-methods:
    - OPTIONS
    - GET
    - PATCH
    - POST
    - PUT
    - DELETE
  # Set super admin email addresses here
  super-admins:
    - pumasemj@gmail.com
    - pumasemj@hotmail.com


springdoc:
  packages-to-scan: com.halildurmus.hotdeals
  swagger-ui:
    layout: BaseLayout
    operationsSorter: method
    path: /swagger-ui
    tags-sorter: alpha

swagger:
  description: "hotdeals REST API Documentation"
  title: "hotdeals API"
  version: "1.0.0"

#logging:
#  level:
    #org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    #root: INFO  # Sets the root logging level
#    com.halildurmus.hotdeals: DEBUG  # Your application package
    #org.springframework: INFO