api-version: "1.0"
spring:
  cache:
    redis:
      cache-null-values: false
      time-to-live: PT10M
  data:
    mongodb:
      auto-index-creation: true
      database: db
      #uri: mongodb://localhost:27017
    rest:
      detection-strategy: annotated
#  elasticsearch:
#    rest:
#      uris: localhost:9200
#  redis:
#    host: localhost
#    port: 6379
security:
  allowed-origins:
    - http://localhost:3000
  allowed-methods:
    - OPTIONS
    - GET
    - PATCH
    - POST
    - PUT
    - DELETE
  # SET THE ADMIN EMAIL ADDRESSES HERE
  super-admins:
    - admin1@gmail.com
    - admin2@gmail.com

springdoc:
  packages-to-scan: com.halildurmus.hotdeals
  swagger-ui:
    layout: BaseLayout
    operationsSorter: method
    path: /swagger-ui
    tags-sorter: alpha

swagger:
  contact:
    name: "Halil Ibrahim Durmus"
    email: "halildurmus97@gmail.com"
    url: "https://github.com/halildurmus"
  description: "hotdeals REST API Documentation"
  title: "hotdeals API"
  version: "1.0.0"