management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cache:
    redis:
      cache-null-values: false
      time-to-live: PT10M
  data:
    # IF YOU'VE USED DOCKER-COMPOSE TO SET UP THE DATABASES YOU CAN LEAVE THIS COMMENTED OUT
    # SINCE THESE ARE THE DEFAULT VALUES
    mongodb:
      auto-index-creation: true
      database: db
      uri: mongodb://localhost:27017
    rest:
      detection-strategy: annotated
  #elasticsearch:
    #rest:
      #uris: localhost:9200
  #redis:
    #host: localhost
    #port: 6379
  profiles:
    active: dev
security:
  firebase-props:
    # SET YOUR FIREBASE AUTHENTICATION DATABASE URL
    database-url: https://xxxxx-xxxx.firebaseapp.com
  allow-credentials: true
  allowed-origins:
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /categories
    - /stores
  exposed-headers:
    - X-Xsrf-Token
  valid-application-roles:
    - ROLE_ADMIN
    - ROLE_SUPER
    - ROLE_MODERATOR
  # SET THE ADMIN EMAIL ADDRESSES HERE
  super-admins:
    - admin1@gmail.com
    - admin2@gmail.com